#services:
#  e2e-web-reference:
#    build:
#      context: .
#      target: test
#      dockerfile: ./Dockerfile
#    ports:
#      - "5000:80"
#    links:
#      - e2e-db
#  e2e-web-current:
#    build:
#      context: /tmp/e2e/reference/
#      target: test
#      dockerfile: ./Dockerfile
#    ports:
#      - "5000:80"
#    links:
#      - e2e-db
#  e2e-db:
#    image: mdillon/postgis:9.6-alpine
#    environment:
#      - POSTGRES_HOST_AUTH_METHOD=trust